name: UI Test

on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-tests:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    
    steps:
    - run: "ui test overrided"  
