name: ui-test

on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  ui-tests:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        containers: [1, 2, 3, 4]

    steps:
    - run: echo "ui tested"
