name: ui-test

on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:

jobs:
  ui-tests:
    if: ${{ github.event.label.name == 'test' }}
    runs-on: ubuntu-latest
    
    steps:
    - run: echo "ui tested"
